"""Initial_migration

Revision ID: b5e6690e9a90
Revises: None
Create Date: 2026-06-07 23:01:59.846832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e6690e9a90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get database inspector to check existing tables
    from sqlalchemy.engine import reflection
    bind = op.get_bind()
    insp = reflection.Inspector.from_engine(bind)
    tables = insp.get_table_names()

    if 'vaccinations' in tables:
        # Table already exists (existing SQLite database).
        # We only add the missing columns.
        columns = [col['name'] for col in insp.get_columns('vaccinations')]
        if 'sms_delivery_status' not in columns:
            op.add_column('vaccinations', sa.Column('sms_delivery_status', sa.String(length=50), nullable=True))
        if 'sms_sent_at' not in columns:
            op.add_column('vaccinations', sa.Column('sms_sent_at', sa.DateTime(timezone=True), nullable=True))
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('alerts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('target_language', sa.String(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('sent_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('faq_cache',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('query_hash', sa.String(length=64), nullable=False),
        sa.Column('original_query', sa.Text(), nullable=False),
        sa.Column('translated_query', sa.Text(), nullable=False),
        sa.Column('resolved_intent', sa.String(length=100), nullable=True),
        sa.Column('answer_text', sa.Text(), nullable=False),
        sa.Column('hits', sa.Integer(), nullable=False),
        sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_faq_cache_query_hash'), 'faq_cache', ['query_hash'], unique=True)
        op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('language_preference', sa.String(length=10), nullable=False),
        sa.Column('onboarded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
        op.create_table('conversations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('channel', sa.String(length=20), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('vaccinations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('vaccine_name', sa.String(length=100), nullable=False),
        sa.Column('dose_number', sa.Integer(), nullable=False),
        sa.Column('scheduled_date', sa.Date(), nullable=False),
        sa.Column('administered_date', sa.Date(), nullable=True),
        sa.Column('notification_sent', sa.Boolean(), nullable=False),
        sa.Column('sms_delivery_status', sa.String(length=50), nullable=True),
        sa.Column('sms_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('conversation_id', sa.UUID(), nullable=False),
        sa.Column('sender', sa.String(length=10), nullable=False),
        sa.Column('original_text', sa.Text(), nullable=False),
        sa.Column('translated_text', sa.Text(), nullable=True),
        sa.Column('language_code', sa.String(length=10), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('vaccinations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_faq_cache_query_hash'), table_name='faq_cache')
    op.drop_table('faq_cache')
    op.drop_table('alerts')
    # ### end Alembic commands ###
